# Dictionary to retrieve the scaling factor for each scale or symbol.
scales = {'quetta': 10 ** 30,
          'ronna': 10 ** 27,
          'yotta': 10 ** 24,
          'zetta': 10 ** 21,
          'exa': 10 ** 18,
          'peta': 10 ** 15,
          'tera': 10 ** 12,
          'giga': 10 ** 9,
          'mega': 10 ** 6,
          'kilo': 10 ** 3,
          'hecto': 10 ** 2,
          'deka': 10,
          None: 1,
          'deci': 10 ** -1,
          'centi': 10 ** -2,
          'milli': 10 ** -3,
          'micro': 10 ** -6,
          'nano': 10 ** -9,
          'pico': 10 ** -12,
          'femto': 10 ** -15,
          'atto': 10 ** -18,
          'zepto': 10 ** -21,
          'yocto': 10 ** -24,
          'ronto': 10 ** -27,
          'quecto': 10 ** -30,
          # Also included symbols for completion.
          'Q': 10 ** 30,
          'R': 10 ** 27,
          'Y': 10 ** 24,
          'Z': 10 ** 21,
          'E': 10 ** 18,
          'P': 10 ** 15,
          'T': 10 ** 12,
          'G': 10 ** 9,
          'M': 10 ** 6,
          'k': 10 ** 3,
          'h': 10 ** 2,
          'da': 10,
          # None: 1, (redundant)
          'd': 10 ** -1,
          'c': 10 ** -2,
          'm': 10 ** -3,
          'μ': 10 ** -6,
          'n': 10 ** -9,
          'p': 10 ** -12,
          'f': 10 ** -15,
          'a': 10 ** -18,
          'z': 10 ** -21,
          'y': 10 ** -24,
          'r': 10 ** -27,
          'q': 10 ** -30}
# Abbreviate names to symbols          
abbreviations = {'quetta': 'Q',
                 'ronna': 'R',
                 'yotta': 'Y',
                 'zetta': 'Z',
                 'exa': 'E',
                 'peta': 'P',
                 'tera': 'T',
                 'giga': 'G',
                 'mega': 'M',
                 'kilo': 'k',
                 'hecto': 'h',
                 'deka': 'da',
                 None: '',
                 'deci': 'd',
                 'centi': 'c',
                 'milli': 'm',
                 'micro': 'μ',
                 'nano': 'n',
                 'pico': 'p',
                 'femto': 'f',
                 'atto': 'a',
                 'zepto': 'z',
                 'yocto': 'y',
                 'ronto': 'r',
                 'quecto': 'q'}
# Convert symbols to names
symbols = {'Q': 'quetta',
           'R': 'ronna',
           'Y': 'yotta',
           'Z': 'zetta',
           'E': 'exa',
           'P': 'peta',
           'T': 'tera',
           'G': 'giga',
           'M': 'mega',
           'k': 'kilo',
           'h': 'hecto',
           'da': 'deka',
           '': None,
           'd': 'deci',
           'c': 'centi',
           'm': 'milli',
           'μ': 'micro',
           'n': 'nano',
           'p': 'pico',
           'f': 'femto',
           'a': 'atto',
           'z': 'zepto',
           'y': 'yocto',
           'r': 'ronto',
           'q': 'quecto'}
